import requestCreator from "@/utils/requestCreator";
export default requestCreator({
    fetchFileList: "/jtyh/qlqxgl/busiqlqxgl/getwjlist",
    fetchFileChapter: "/jtyh/qlqxgl/busiqlqxgl/getzjlist",
    fetchDefectList: "/jtyh/qlqxgl/busiqlqxgl/getqxlist",
    deleteFile: "/jtyh//qlqxgl/busiqlqxgl/deletewj",
    uploadFile: "/jtyh/qlqxgl/busiqlqxgl/importfile",
    updateConfig: "/jtyh/qlqxgl/busiqlqxgl/updateqxcfg",
    exportfile: "/jtyh/qlqxgl/busiqlqxgl/exportfile",
    fetchRuleList: "/jtyh/qlqxgl/basqxglcfg/getcfglist",
    fetchRuleItem: "/jtyh/qlqxgl/basqxglcfg/getcfgitem",
    safeRule: "/jtyh/qlqxgl/basqxglcfg/savecfg",
    fetchSolutionOption: {
        url: "/jtyh/qlqxgl/basqxglcfg/getczfalist",
        hideLoading: true,
    },
    saveSolutionConfig: "/jtyh/qlqxgl/busiqlqxgl/saveqxfa",
    deleteSolution: "/jtyh/qlqxgl/busiqlqxgl/deleteqxfa",
    fetchSolutionList: "/jtyh/qlqxgl/basqxglcfg/getczfalist",
    fetchSolutionItem: "/jtyh/qlqxgl/basqxglcfg/getczfaitem",
    saveSolution: "/jtyh/qlqxgl/basqxglcfg/saveczfa",
    fetchFileItem: "/jtyh/qlqxgl/busiqlqxgl/getwjitem",
    saveFile: "/jtyh/qlqxgl/busiqlqxgl/savewj",
    fetchBridgeException: "/jtyh/qlqxgl/busiqlqxgl/getycqxlist",
    fetchTunnelException: "/jtyh/qlqxgl/busisdqxgl/getycqxlist",
});
